<div class="account-login">
<div class="page-title">
    <h3><?php echo $this->__('Log in or Create an Account') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col2-set">
<form action="<?php echo $this->getRegisterPostActionUrl() ?>" method="post" id=register-form">
    <div class="col-1 new-users">
        <div class="content">
            <h4><?php echo $this->__('New Customers') ?></h4>
            <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
        </div>
        <div class="button-set">
            <button type="submit" class="button right" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';" type="button"><span><?php echo $this->__('Create an Account') ?></span></button>
        </div>
    </div>
</form>	
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
    <div class="col-2 registered-users">
        <div class="content">
            <h4><?php echo $this->__('Registered Customers') ?></h4>
            <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
            <ul class="form-list">
                    <li>
                        <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
                        <input name="email" value="" title="<?php echo $this->__('Email Address') ?>" id="email" type="text" class="input-text required-entry" style="width:250px;" />
                    </li>
                    <li>
                        <label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
                        <input name="pass" type="password" class="input-text required-entry validate-password" id="pass" style="width:250px;" />
                    </li>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    </div>
	<div class="col-2 registered-users">
    <div class="button-set">
        <!--<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="left"><?php echo $this->__('Forgot Your Password?') ?></a>-->
        <button class="button right" type="submit" name="send" id="send2"><span><?php echo $this->__('Login') ?></span></button>
    </div>
</div>
</div>
</form>
</div>
<script type="text/javascript">
    var dataForm = new VarienForm('login-form', true);
	 var dataForm = new VarienForm('register-form', true);
</script>
</div>